# dataset:
#   _name_: forex
#   data_dir: ./data/informer/forex
#   seq_len: 30
#   pred_len: 1
#   val_split: 0.1
#   seed: 42
#   batch_size: 1
#   normalize: true
#   size:
#     - 384
#     - 96
#     - 96
#   variant: 0
#   scale: true
#   inverse: false
#   timeenc: 1
#   eval_stamp: false
#   eval_mask: false
_name_: forex
size:
  - 384
  - 96
  - 96
features: 'S'
target: 'open'
variant: 0
scale: True
inverse: False
timeenc: 0
eval_stamp: False
eval_mask: False
# freq: 'h'
__l_max: ${eval:${.size.0}+${.size.2}}
